### ISSUE TITLE
无法输出正常节点信息

### ISSUE THREAD

**Issue by MrCloudyGod** [chise0713/warp-reg.sh#2]
[root@]# bash -c "$(curl -L warp-reg.vercel.app)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4142  100  4142    0     0   9061      0 --:--:-- --:--:-- --:--:--  9061
Algorithm X25519 not found
unable to load key
140077918467984:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: ANY PRIVATE KEY

ERROR: "reg" function returned with 1, exiting.

**Comment by chise0713** [comment]
运行环境是否有完整的 openssl 支持

**Comment by MrCloudyGod** [comment]
> 运行环境是否有完整的 openssl 支持

[root@racknerd-511257 ~]# yum install openssl
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.ocf.berkeley.edu
 * elrepo: mirror.rackspace.com
 * extras: mirrors.raystedman.org
 * updates: mirror.web-ster.com
Package 1:openssl-1.0.2k-26.el7_9.x86_64 already installed and latest version
Nothing to do
[root@racknerd-511257 ~]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

新vps,centos7自带的

**Comment by chise0713** [comment]
需要 openssl v1.1.0 及以上

**Comment by MrCloudyGod** [comment]
> 需要 openssl v1.1.0 及以上

感谢，已解决！
