### ISSUE TITLE
replace python3 and xxd with jq

### ISSUE THREAD

**Issue by ghost** [chise0713/warp-reg.sh#3]
because python3 is very huge, and xxd is not always available on different operating systems; so please replace them with jq

**Comment by chise0713** [comment]
Can `jq` convert text to hex ?

**Comment by ghost** [comment]
no, jq can't

jq can be used to replace "python3 -m json.tool"

**Comment by ghost** [comment]
but it's quite easy to convert text to hex with bash shell

tell me some examples about the desired input and output patterns, i will create a shell script to convert them

**Comment by chise0713** [comment]
> but it's quite easy to convert text to hex with bash shell
> 
> tell me some examples about the desired input and output patterns, i will create a shell script to convert them

https://github.com/chise0713/warp-reg.sh/blob/b7ba91e55c2be20321c5ec9386b92e5dfcb26824/warp-reg.sh#L49-L62
Refer its output's `config.client_id`

**Comment by chise0713** [comment]
You can directly open a pull request include your function to replace `xxd`

**Comment by chise0713** [comment]
> jq can be used to replace "python3 -m json.tool"

- bf250a22c89b9c860e59b6f2cf0ad00391ef0ce6
Replaced

**Comment by CrazyDigital** [comment]
that's great!

i did the later:

`xxd -r -p` (hex to str) can be replaced by `awk '{gsub(/../,"0x& ");for(i=1;i<=NF;i++)printf("%c",strtonum($i));print ""}'`

`xxd -p` (str to hex) can re replaced by ` od -An -t x1`

**Comment by chise0713** [comment]
Since the author is gone, closing.
